name: clibgen-test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  clibgen-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v4
      -
        name: Run Build
        run: go build 
      -
        name: Run Tests
        run: go test ./test
